### ISSUE TITLE
Project updater error if slash is forgotten

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#263]
Ideally Roam just adds it if it is missing:

Traceback (most recent call last): 
File "roam\updater.pyc", line 236, in list_versions 
File "roam\updater.pyc", line 30, in parse_serverprojects 
File "yaml\__init__.pyc", line 71, in load 
File "yaml\constructor.pyc", line 37, in get_single_data 
File "yaml\composer.pyc", line 39, in get_single_node 
File "yaml\parser.pyc", line 98, in check_event 
File "yaml\parser.pyc", line 174, in parse_document_start 
ParserError: expected '', but found '' in "", line 14, column 1: background-color:#555555;} ^

**Comment by bzeeb** [comment]
![image](https://cloud.githubusercontent.com/assets/5965006/7176400/a02817e6-e450-11e4-9a92-96ddf7c4493e.png)
