### ISSUE TITLE
Unable to save feature with a form that has no image.

### ISSUE THREAD

**Issue by PhilipWhitten** [DMS-Aus/Roam#383]
If I complete a form, but leave the image empty I get the following error:

Error: AttributeError: 'NoneType' object has no attribute 'save'
Traceback (most recent call last):
  File "C:\IntraMaps Roam Road Tablet\libs\.\roam\editorwidgets\featureformwidget.py", line 105, in save_feature
  File "C:\IntraMaps Roam Road Tablet\libs\.\roam\api\featureform.py", line 866, in save
  File "C:\IntraMaps Roam Road Tablet\libs\.\roam\api\featureform.py", line 848, in save_images
  File "C:\IntraMaps Roam Road Tablet\libs\.\roam\editorwidgets\imagewidget.py", line 491, in save
  File "C:\IntraMaps Roam Road Tablet\libs\.\roam\editorwidgets\imagewidget.py", line 112, in save_image
AttributeError: 'NoneType' object has no attribute 'save'

**Comment by bzeeb** [comment]
Tested, issue resolved
