### ISSUE TITLE
Expression - Simple value   return field maxium+1 bug

### ISSUE THREAD

**Issue by Lendog** [DMS-Aus/Roam#405]
the below simple value expression 
![image](https://user-images.githubusercontent.com/17174019/35955760-8ef873c4-0ce5-11e8-8dd4-a15e033cc765.png)

crashes roam form with 
![image](https://user-images.githubusercontent.com/17174019/35955750-77795236-0ce5-11e8-82f0-bacd12af9f33.png)

In the expression string builder returns a sensible result
![image](https://user-images.githubusercontent.com/17174019/35955775-ae24e4da-0ce5-11e8-9373-6832ab5bf07e.png)

**Comment by bzeeb** [comment]
Will investigate.

**Comment by she-weeds** [comment]
Hi, I'm experiencing the same issue in 2.6.0 as well; sensible output in expression editor but an error when adding new features. Was investigating an alternative to the ROAM max_value() function (and aggregate() version which functions the same way) as both don't auto-increment when I have other fields repeating from the last feature in the form. 

I get the same error when not wrapping "treeid" in to_int()

Error log:
Something has gone wrong.
Error: ValueError: invalid literal for int() with base 10: '[% to_int(maximum(to_int("treeid")))+1 %]'
Traceback (most recent call last):
  File "roam\mainwindow.pyc", line 449, in openForm
  File "roam\dataentrywidget.pyc", line 178, in load_feature_form
  File "roam\dataentrywidget.pyc", line 78, in add_widget
  File "roam\editorwidgets\featureformwidget.pyc", line 178, in setvalue
  File "roam\editorwidgets\featureformwidget.pyc", line 134, in bind_values
  File "roam\api\featureform.pyc", line 513, in bindvalues
  File "roam\editorwidgets
umberwidget.pyc", line 105, in setvalue
ValueError: invalid literal for int() with base 10: '[% maximum(to_int("treeid"))+1 %]'
